// Loads the static config/problems JSON generated by build/build_problems.py.
// Cached in-module for the lifetime of the page (they never change at runtime).

let cache = null;

export async function loadData() {
  if (cache) return cache;
  const [config, problemsRaw, examsRaw, packagesRaw] = await Promise.all([
    fetch("data/config.json").then((r) => r.json()),
    fetch("data/problems.json").then((r) => r.json()),
    fetch("data/exams.json").then((r) => r.json()),
    fetch("data/packages.json").then((r) => r.json()),
  ]);
  const problems = [...problemsRaw.leadalpha, ...problemsRaw.juyomon];
  cache = {
    config,
    problems,
    leadalpha: problemsRaw.leadalpha,
    juyomon: problemsRaw.juyomon,
    exams: examsRaw.exams,
    packages: packagesRaw.packages,
  };
  return cache;
}
